### ISSUE TITLE
Sort names in the alphabetical list by last name

### ISSUE THREAD

**Issue by lislis** [rubymonsters/slam-alphas#105]
We save the name in one field and sort by that. 
This naturally leads to sorting by first name but the alphas want sorting by last name (or if only one name is given by that).
I implemented this on the wordpress site (see screenshot) by splitting the name by `' '` and then sort it by the last element (equivalent of last name).

![screen shot 2017-05-24 at 15 17 05](https://cloud.githubusercontent.com/assets/1006478/26404989/1c232fce-4094-11e7-97b1-ba8eacb3c8fe.png)

**Comment by joecorcoran** [comment]
Closed by #142
