### ISSUE TITLE
Add a homepage

### ISSUE THREAD

**Issue by freddax** [rubymonsters/slam-alphas#11]

**Comment by joecorcoran** [comment]
The blank page was added by #15 – waiting now for design/content.

**Comment by joecorcoran** [comment]
We can possibly close this one, since the homepage is now a part of the Wordpress site...?

**Comment by lislis** [comment]
Yes! I set the root route to `karte/de` in https://github.com/rubymonsters/slam-alphas/pull/40/commits/160785765e41554da474c52bba55061027d676ee
Closing this
