### ISSUE TITLE
Create a 404 page

### ISSUE THREAD

**Issue by lislis** [rubymonsters/slam-alphas#124]
nothing fancy, just so the app doesn't look broken :)

**Comment by lislis** [comment]
I think someone started working on this? But I can't remember who?
I can ask the Alphas for a photo or something to be displayed if wanted, just ping me

**Comment by CarolinaGri** [comment]
Hi LIsa, was me. I will start to work on the ticket now. Yes sure if you have a picture, let me know.

**Comment by lislis** [comment]
Shipped!

**Comment by CarolinaGri** [comment]
http://karte.slamalphas.org/karte/de/404.html is not loading the picture- just in my browser?

**Comment by lislis** [comment]
Ah, true. Here is the missing piece:
![screen shot 2017-08-08 at 11 04 50](https://user-images.githubusercontent.com/1006478/29064523-834d7da0-7c29-11e7-86e5-d449c2c13fb3.png)
We need a `/` before the background-image path, otherwise it doesn't seem to work on the server.

@CarolinaGri do you want to fix it?
