### ISSUE TITLE
Change form of available on to checkboxes

### ISSUE THREAD

**Issue by lislis** [rubymonsters/slam-alphas#129]
I got feedback that the multiselect dropdown will probably not work for them. They need an 'idiotensicher' solution with eg checkboxes for each option.
An implementation like this will probably also solve https://github.com/rubymonsters/slam-alphas/issues/126

@1000miles can I assign you here?

**Comment by 1000miles** [comment]
hey @lislis ! yes, of course but i can assign it to myself, too. :)
