### ISSUE TITLE
[DB] provide user example data to seed into database

### ISSUE THREAD

**Issue by CarolinaGri** [rubymonsters/slam-alphas#47]
## issue:
In the moment, if we reset the database it takes effort to refill the data manually

## possible approach:
- Fill the seed.rb with data examples (to accelerate the process of seeding data into the database) 
- Install and implement the gem `faker` to retrieve user data quicker

**Comment by joecorcoran** [comment]
Just noticed that there's also https://github.com/rubymonsters/slam-alphas/issues/29

**Comment by 1000miles** [comment]
Helpful commands:

## Log into the rails console (dev environment)
```
$ bundle exec rails c
```

## Count how many users are existent in the console
```
users = User.all
users.count
```

## Delete all users and check if it returns `0` users
```
users.delete_all
users.count
```

## Seed the example data from `db/seed.rb`
```
RAILS_ENV=development bundle exec rake db:seed
```

## Log back into the console to check the new 37 users are created
```
users = User.all
users.count
```

**Comment by 1000miles** [comment]
Closing this ticket since PR #49 is approved and merged.
