### ISSUE TITLE
[Security] Create an env.SAMPLE file

### ISSUE THREAD

**Issue by 1000miles** [rubymonsters/slam-alphas#51]
At the moment some of us use different systems (mac os x, ubuntu, etc.) to work on the project. If we use an `.env` file (hidden, not checked into Git) on our local computers we can store credentials and configs.

### Benefits:
a) We don't need to worry about if sensitive data is revealed, e.g. URL, passwords, etc.
b) We can use different configs dependent on the operating system of each of us, e.g. PATH_TO_A_LIBRARY
c) We can store data dependent on the environment (development/test/production) we use.

---

**Update, 2017-2-14:**

In order to use the `env.SAMPLE` file we need to copy its content to `.env` and modify the settings according to everyone's needs. 

Following links might help to understand what env variables are about:
- Managing Environment Configuration Variables in Rails - https://launchschool.com/blog/managing-environment-configuration-variables-in-rails/
- gem [dotenv](https://github.com/bkeepers/dotenv) to load dotfiles before other gems, e.g fog-aws (that require credentials)
- Environment Variables - https://www.youtube.com/watch?v=O-aDLsuNTRY
- Environment Variables in Ruby on Rails - https://richonrails.com/articles/environment-variables-in-ruby-on-rails

**Comment by 1000miles** [comment]
Cool, thanks for the PR #61 . :)

Basically the `.env` file is the one that shouldn't be checked into Git because here you put all the sensitive data that shouldn't be visible to the public. It stays in your **project root** and is only visible to you. And here comes the concept behind it.

1. Provide an `env.SAMPLE` with placeholder content like this (just an example):
```shell
# Production credentials
DATABASE_URL=<PUT THE POSTGRES DATABASE URL HERE>
DATABASE_NAME=<PUT THE SLAM ALPHAS DATABASE NAME HERE>
DB_USERNAME=<PUT THE DB USERNAME HERE> # The user who can log into the database
DB_PASSWORD=<PUT THE DB PASSWORD HERE>

# Production secrets
SECRET_KEY_BASE=<PUT YOUR SECRET TOKEN HERE> # Generate your personal secret token via 'bundle exec rake secret'
```

2. Let people know they should copy the file like this (for example in the README.md):
```SHELL
$ cp env.SAMPLE .env
```

3. After the `.env` file is created, fill in the placeholder text. Comment out all parts you currently don't use.

In order to get the production credentials for your `.env` file you could for example run in the terminal (make sure to be in the project directory):
```
$ heroku config
```

This should then show you the credentials that is associated with our current production database configs on heroku.

4. Now make sure to not check this file into git by putting it to the file `.gitignore`.
```SHELL
.env
```
Some gems require to load the credentials first before they can execute (e.g. `fog/aws`), means we need to make sure the `.env` file is loaded before those gems are running, e.g. by using a gem like `dotenv`.

Since you already checked the `.env` file into git with PR #61 I would suggest you close this PR (unmerged) and create a new one with the `env.SAMPLE` file? This way we make sure `.env` will never be checked into git. What do you think?

Does that all make sense to you? I hope I did not write any nonsense. :)

**Comment by lislis** [comment]
Updated, rebased and merged the PR
![clap clap](https://media.giphy.com/media/DnR5sy5P3hcCk/giphy.gif)
