### ISSUE TITLE
Error when trying to submit empty sign_in form

### ISSUE THREAD

**Issue by lislis** [rubymonsters/slam-alphas#54]
When trying to submit an empty aign_in form
<img width="786" alt="screen shot 2017-02-13 at 19 32 33" src="https://cloud.githubusercontent.com/assets/1006478/22897375/b8920214-f223-11e6-8f23-59654e4884cc.png">

I get
<img width="833" alt="screen shot 2017-02-13 at 19 32 39" src="https://cloud.githubusercontent.com/assets/1006478/22897383/be1a3d3c-f223-11e6-86bf-a26c90f4796d.png">

**Comment by CarolinaGri** [comment]
There is nothing happening within my browser when I leave the form empty and submit:

![screen shot 2017-05-08 at 21 40 34](https://cloud.githubusercontent.com/assets/15719995/25821901/184ab71e-3437-11e7-9fe6-a6851002b744.png)

**Comment by CarolinaGri** [comment]
The issue was apparently  already been fixed due to other changes.
