### ISSUE TITLE
[Frontend] Long city names are overlapping over border of user list box

### ISSUE THREAD

**Issue by CarolinaGri** [rubymonsters/slam-alphas#57]
Long city names are overlapping over border of user list - please find as follows in picture

Example:
Taumatawhakatangihangakoauauotamateapokaiwhenuakitanatahu

![screen shot 2017-02-13 at 21 30 22](https://cloud.githubusercontent.com/assets/15719995/22902059/06fffe46-f234-11e6-83f1-768f32282301.png)

**Comment by CarolinaGri** [comment]
Maybe that would be an option?
`word-wrap: break-word`

**Comment by lislis** [comment]
coming up in https://github.com/rubymonsters/slam-alphas/pull/82/commits/bd8c91f07c4772424e4e709e158edc6b66270ff2

**Comment by lislis** [comment]
closed by https://github.com/rubymonsters/slam-alphas/pull/82
