### ISSUE TITLE
[Frontend] Can not scroll on user edit page

### ISSUE THREAD

**Issue by 1000miles** [rubymonsters/slam-alphas#58]
At the moment after login on an example user ~~detail~~ edit page at `http://192.168.33.15:3456/users/4/edit` I can not scroll from top to down to see all elements of the page. Even after merging the latest PR of design updates today.

**Tested with:**
- Firefox & Google Chrome
- 100% window size

<img width="1194" alt="00000260" src="https://cloud.githubusercontent.com/assets/4077916/22906600/8479b2ca-f245-11e6-8a01-57af683d7c38.png">

**Comment by 1000miles** [comment]
@lislis Would you mind to take care of this task? Unless this is not done, I have problems to really test the image uploads smoothly.

**Comment by lislis** [comment]
👀 ing into it

**Comment by lislis** [comment]
PR here https://github.com/rubymonsters/slam-alphas/pull/63

**Comment by 1000miles** [comment]
Done in PR #63. Closing.
