### ISSUE TITLE
Add User Authentication (login / sign up)

### ISSUE THREAD

**Issue by eine-sandra** [rubymonsters/slam-alphas#6]

**Comment by joecorcoran** [comment]
We might be lucky enough to get a short presentation on this topic from @ariaru...

**Comment by joecorcoran** [comment]
This is not blocked any more – we can start this when I'm back. 🚀

**Comment by joecorcoran** [comment]
- [x] Sign in / Sign out
- [x] New user sign up
- [ ] Change password
- [ ] Forgot password (including email to reset etc.
- [ ] Check forms for password validation errors etc.
- [ ] Which pages should be password protected?
- [ ] Cookie correctly scoped? (domain)

**Comment by joecorcoran** [comment]
We need input from @lislis regarding an email address we can use for password reset emails... is there any admin@slamalphas address yet?

**Comment by lislis** [comment]
@joecorcoran you mean as `from:` email? you can use `info@slamalphas.org`

**Comment by joecorcoran** [comment]
@lislis Cool! We'll probably need to get the SMTP setup and get the details from you. It can wait until next week sometime.

**Comment by lislis** [comment]
Sounds good!

**Comment by joecorcoran** [comment]
Change of plans re: auth

- [ ] Only admins can log in
- [ ] Admins can create new users
- [ ] Admins can decide whether new users are also admins
- [ ] Text and links are updated to reflect this

**Comment by 1000miles** [comment]
Done in PR #46. Closed.
