### ISSUE TITLE
[Feature] Setup waffle.io for better project handling

### ISSUE THREAD

**Issue by 1000miles** [rubymonsters/slam-alphas#60]
At the moment we don't really see the current status of a task. In order to have a better overview I would suggest to use labels like `in-progress`, `on hold`, `review`. As the `projects` feature of Github does not really deliver clear insights, I would suggest to use [waffle](https://waffle.io/) instead. 

Can you please confirm using waffle?
@joecorcoran @lislis

**Comment by lislis** [comment]
Sure, feel free to use whatever you want :)

**Comment by 1000miles** [comment]
Will do, thanks. :)

**Comment by 1000miles** [comment]
Done in PR #62 . 

Slack integration and Waffle bot has been installed by @joecorcoran too today. Closing this ticket.
