### ISSUE TITLE
Add Video Links

### ISSUE THREAD

**Issue by Uschi760** [rubymonsters/slam-alphas#7]
We should argue about this: should it just be a link or some embed video. I guess we decided for the second idea.

**Comment by lislis** [comment]
I think it's best/ easiest to input the link. Then we use a regex to find out if it's a youtube or vimeo link and render the embed code accordingly

**Comment by 1000miles** [comment]
Thanks, makes sense. :)

Referencing ticket: #75

**Comment by lislis** [comment]
Done in #121
