### ISSUE TITLE
Clicking on home / logo on karte.slamalphas.org should redirect to slamalphas.org

### ISSUE THREAD

**Issue by vsmart** [rubymonsters/slam-alphas#71]
Home button (i.e. clicking on logo) on karte.slamalphas.org should redirect to slamalphas.org - currently it stays on karte.slamalphas.org. 

Ping @lislis

**Comment by lislis** [comment]
Fix coming in https://github.com/rubymonsters/slam-alphas/pull/82/commits/bd8c91f07c4772424e4e709e158edc6b66270ff2

**Comment by lislis** [comment]
closed by https://github.com/rubymonsters/slam-alphas/pull/82
