### ISSUE TITLE
Add more profile fields

### ISSUE THREAD

**Issue by lislis** [rubymonsters/slam-alphas#75]
There are still fields missing from profiles. Those can be added step by step

- [x] Link to a video recording - status: `done`
  This can either be youtube or vimeo. We'll just save the link and then display the embedded player. - status: `done` => PR https://github.com/rubymonsters/slam-alphas/pull/102
  For this we'll either need to display radio buttons (youtube or vimeo) or analyze the url and decide for ourselves
- [x] availability on weekends, on work days, during (school) holidays - status: `done`
  Saying something like `is available on ` and then list each selected option (can be multiple) => PR https://github.com/rubymonsters/slam-alphas/pull/102 & PR https://github.com/rubymonsters/slam-alphas/pull/141
- [x] an/ will travel, within 50km radius, within 100km radius, within 300km radius, any distance
  Saying something like `will travel ` and then the selected distance (can be only one) => PR https://github.com/rubymonsters/slam-alphas/pull/127
- [x] travels via car, train, plane - status: `done`=>  PR #145
  Only available if user will travel, can be multiple
- [x] train bonus cards  - status: `done` => PR #148 
   ```
   has Bahncard 25 
   has Bahncard 50
   has Bahncard 100
   has Österreichcard
   Halbtax
   ```
   Only available if user is travelling via train, can be multiple

Feel free to open smaller tickets for each one :)

**Comment by 1000miles** [comment]
@lislis As far as I understood following input fields end up on a user's profile page shown on the path e.g. `/users/1` (user show page)

**Already implemented & visible:**
- name
- city
- country

**Not visible/implemented yet:**
- birth year
- website link
- facebook link
- profile image
- video link (embedded code)
- is available on
- travels via
- will travel
- train bonus cards

Since the class `article.slam-profile` is currently only 300 px x 349 px big I am wondering where all these upcoming elements will be shown in the end? Will there be a link like `See more` and a visitor will be linked to another user profile page with bigger views?

**Comment by lislis** [comment]
Hey @1000miles! Good question!
I added age, website and facebooklink in this PR (still open) https://github.com/rubymonsters/slam-alphas/pull/82/files#diff-c7c9a522f39f5d8cd9b512cd928b2d14

Here is a screenshot of what the designer thought of as profile:
<img width="904" alt="screen shot 2017-05-09 at 23 19 36" src="https://cloud.githubusercontent.com/assets/1006478/25873247/10b857cc-350e-11e7-8dd4-1ccb9434f317.png">

The profile picture will go up next to the name (that is not urgent for now).

We don't have that long description text, instead we'll just list all travel information one by one.

The video (there will only be one for now) will open the next white overlay to the right where we'll have the embedded player.

I hope it all fits underneath each other. Worst case we have to overflow-scroll the container. I'm also working on a solution for smaller devices without the opening/closing overlays.

Does that make some sense?

**Comment by 1000miles** [comment]
@lisis aaah, now i understand. thanks for the clarification. yes, let's see if everything fits underneath.

somehow i did not get an email notification about your review request. will do it tonight or over the weekend. hope you can wait a bit. :)

**Comment by 1000miles** [comment]
@lislis I am currently working on the subtask `will_travel` to use radio buttons but I am unsure here which data type to generate as for the migration? My researches did not result in clear answers so far. Would you mind to give some input here? Thank you. :)

- `will travel` => is this attribute fixed, means no choice for `yes` or `no` (e.g. as check box)?
  - radio buttons => only 1 choice can be selected, are we using the datatype `integer`, e.g. 
    - within 50km => 0 (false)
    - within 100km => 1 (true)
    - within 300km => 0 (false)
    - any distance => 0 (false)
    - no distance => 0 (false)

**Comment by lislis** [comment]
Very good question, I needed to think about this a bit.
How about we store the actual kilometers as integers in the database?
so `0` would mean no distance or will not travel
`50`, `100`, `300` will be the kilometers. This also makes it easier to add more steps.
`any distance` is trickier. Either we just go for an arbitrary huge number like 1000 and use that (and hide it in the user interface) or use `nil` as in 'nil distance means all the distances'.

In the interface we just present them with the options that we decide to show them. Maybe store it as an array and for each option render a radio button.

Wdyt @1000miles ?

**Comment by 1000miles** [comment]
Done. 🎉 🌮 Thanks, @lislis ! :)

Minor changes will be addressed in follow-up tickets. Closing.
