### ISSUE TITLE
[Login] User profile shown on the map doesn't reflect the user who has signed-in

### ISSUE THREAD

**Issue by 1000miles** [rubymonsters/slam-alphas#78]
### Case 1: Login as a non-admin user

- I signed-in as a non-admin user `Chad Harris` with the email address `milo@bode.org` (generated by the gem faker) and user_id: 3.
- After I signed-in I expect to see my own profile under `/users/3` but instead I see only another user `/users/38` which is `Thuy` 

**Screenshot 1:**
<img width="1266" alt="00000282" src="https://cloud.githubusercontent.com/assets/4077916/24624059/eb202410-18aa-11e7-93a7-e05d85fe85f5.png">

- only if I explicitly go to `users/3` I can see my own profile as `Chuck Harris`

**Screenshot 2:**

<img width="1266" alt="00000283" src="https://cloud.githubusercontent.com/assets/4077916/24624148/33960250-18ab-11e7-90e9-7e8572857667.png">

----

### Case 2: Login as an admin user

- I am signed in as an admin user
- As an admin I should see all user profiles on the map, instead I only see 1 profile that is flagged as public under `/users/56`

**Comment by 1000miles** [comment]
Maybe related to 

Github ticket: #55 
PR: #70

**Comment by lislis** [comment]
I believe this is also done?

**Comment by 1000miles** [comment]
Yes, this is fixed. I tested it. Thanks. Closing.
