### ISSUE TITLE
Sign up broken/ Bad Signup UX?

### ISSUE THREAD

**Issue by lislis** [rubymonsters/slam-alphas#83]
When I try to make a new profile when not logged in, it does not safe the user.
I believe that's a restriction for not-logged in users/ non-admins.
But! It would be much better if I could not even access the routes for that if I don't actually have the permission to do so

**Comment by joecorcoran** [comment]
Suggestion: redirect away from `users#new` unless the user is signed in.

https://github.com/rubymonsters/slam-alphas/blob/master/app/controllers/users_controller.rb#L35

**Comment by aydamacink** [comment]
Don´t render the signup for unless the user is an admin because only admins can create profiles, so if the user is not an admin redirect someplace else

**Comment by lislis** [comment]
Heeeey and sorry!
With recent communication outlined here https://github.com/rubymonsters/slam-alphas/issues/85
We don't need the redirect, but rather just have the sign up work for new users again

**Comment by joecorcoran** [comment]
Seems like this will be fixed by #85, so closing.
