### ISSUE TITLE
Sign up flow again!

### ISSUE THREAD

**Issue by lislis** [rubymonsters/slam-alphas#85]
So after some back and forth, here is what the Alphas want as the final signup process.
I know this is basically what we had in the beginning, sorry :/

- Slammerin wants to be on the map and goes to the Slam Alphas page
  -> We probably need to add a link to the app. I will also add one to the Wordpress page but I don't think that's enough (https://github.com/rubymonsters/slam-alphas/issues/88)
- Slammerin creates an account an has the possibility to add all the information
  - They want ALL fields to be required to create an account (https://github.com/rubymonsters/slam-alphas/issues/89)
  - We also need to add a field to the signup form which Alpha referenced them. I'll open an issue with more details (https://github.com/rubymonsters/slam-alphas/issues/86  https://github.com/rubymonsters/slam-alphas/issues/87)
  - That would be all except for `public` and `alpha` which only an admin can set
- Emails are sent:
   1) email to the admins (`redaktion[at]slamalphas[dot]org`) that a new account has been created, 
  2) email to the Slammerin saying 'Wir haben deine Anfrage erhalten und prüfen sie. Du bekommst eine Mail wenn alles online ist'.
- Admin look through the profile and can set the profile to `public=true`
- Slammerin receives an email saying `Dein Profil ist jetzt online <link>`

**Comment by joecorcoran** [comment]
- [x] Users can sign up now
- [x] All fields required
- [ ] Email to admins when a new user is created
- [ ] Email to user saying to wait for approval
- [ ] Email to user when admin approves user

**Comment by joecorcoran** [comment]
Ping @lislis – this is ready to test :)

**Comment by joecorcoran** [comment]
This PR needs `MAILGUN_USERNAME` and `MAILGUN_PASSWORD` env vars to send emails.

**Comment by lislis** [comment]
Closed by #101
