### ISSUE TITLE
Make all fields requried except for public and alpha

### ISSUE THREAD

**Issue by lislis** [rubymonsters/slam-alphas#89]

**Comment by joecorcoran** [comment]
This is fixed in #85

**Comment by 1000miles** [comment]
@joecorcoran You wrote 
> This is fixed in #85

But #85 is an issue not a PR, so where can I find this fix? Will this be a separate upcoming PR? I am asking because I was about to make the more input fields mandatory in issue #75. Thanks for clarification. :)
