### ISSUE TITLE
Create emails

### ISSUE THREAD

**Issue by lislis** [rubymonsters/slam-alphas#90]
We need three emails:

- [x] Notification for admins if a new profile was created
- [x] Notification for newly signed up person that profile creation was successful but is not online yet
- [x] Notification for newly signed up person that their profile is online now

_note: online meaning public_

**Comment by joecorcoran** [comment]
Still waiting for the SPF record to propagate...

**Comment by lislis** [comment]
This is also live now! Not sure if we want to consider this for local setups differently.
We will at some point get copy for the emails from the Alphas but there is no urgency

**Comment by lislis** [comment]
Closed by #101
